config/routes.rb
Rails.application.routes.draw do
  
  get 'cards/new'

  root 'page#start'

  get '/play' , to: 'cards#play'

  get '/result', to: 'cards#result'
  
  get '/about', to: 'page#about'
  
  delete '/cards/:id', to: 'cards#change'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :content, presence: true
end

app/models/display_card.rb
class DisplayCard < ApplicationRecord
  validates :displaycon, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
  end
  def play
    @displaycards =DisplayCard.all
    
  end
  def result
    @displaycards =DisplayCard.all
  end
  def change

      @leave=cookies[:card_ids].split("a");
      @card_num=rand(0..@leave.size-1)
      DisplayCard.find(params[:id]).update_attributes(displaycon: Card.find(@leave[@card_num]).content)
      cookies[:card_ids]=cookies[:card_ids].sub("#{@leave[@card_num]}a","")
    if cookies[:card_ids] != ""    
      redirect_to play_path
    else
      redirect_to result_path
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def start
    cookies[:card_ids]=""
    for i in 1..Card.last.id
      cookies[:card_ids]="#{i}a#{cookies[:card_ids]}"
    end
    
    for i in 1..5 do
      @leave=cookies[:card_ids].split("a");
      @card_num=rand(0..@leave.size-1)
      
      DisplayCard.find(i).update_attributes(displaycon: Card.find(@leave[@card_num]).content)
      cookies[:card_ids]=cookies[:card_ids].sub("#{@leave[@card_num]}a","")
    end
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title="")
    base_title="PeopleTech"
    if page_title.empty?
      base_title
    else
      page_title+" | "+base_title
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/cards/new.html.erb
<h1>Cards#new</h1>
<p>Find me in app/views/cards/new.html.erb</p>

app/views/cards/play.html.erb
<%provide(:title, "Play")%>
<div class="pt">
  <ul class="cards">
  <table align="center">
    <% @displaycards.each do |displaycard| %>
      <%= render displaycard %>
    <% end %>
  </table>
</ul>
<p class="sample" style="text-align:center;">
<button class='button'>
  <%=link_to 'result' ,result_path %>
</button>
</p>
</div>

app/views/cards/result.html.erb
<%provide(:title, "Result")%>
  <% @displaycards.each do |displaycard| %>
  <ul style="text-align:center;" class='pt'>
    <%= displaycard.displaycon %>
  </ul>
<% end %>

app/views/display_cards/_display_card.html.erb
<tr>
  <div  style="text-align:center;" ></div>
  <th><%= display_card.displaycon %></th>
  <th><button class="button"><%=link_to "change" , "/cards/#{display_card.id}", method: :delete %></button></th>
</tr>

app/views/layouts/_header.html.erb
<div class='pt'>
  <p style="text-align:right;">
    <%=link_to 'start' ,root_path %>
    <%=link_to 'about' ,about_path %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= yield %>      
  </body>
</html>

app/views/page/about.html.erb
<%provide(:title, "About")%>
<div class="pt" style="text-align:center;">
    <div>
        このゲームは価値観の抽出を行います。</br>
        スタートボタンを押すと、5つの言葉が表示されます。</br>
        その中から自分の価値観とは違うものを一つ選び、チェンジボタンを押す。</br>
        すると新しい言葉に変わります。複数回繰り返し、最終的に残ったものがあなたの価値観を表しています。</br>
        チェンジする言葉がなくなった場合、resultボタンを押すと結果画面に移ります。
    </div>
</div>

app/views/page/start.html.erb
<%provide(:title, "Start")%>
<div class="pt" style="text-align:center;">
<h1>People Tech</h1>
<button class = "button"><%= link_to "スタート" ,play_url %></button>
</div>